<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="blog"><a href="#blog">Blog</a></h1>
    <p>Comenzando con mi DevBlog, primero presentaciones:</p>
    <p>
      Soy Alejandro Baeza, un artista 3D de Madrid(España) y tengo 25 años. Actualmente llevo 4 años en 3D y me
      especializo en el apartado Técnico del Arte.
    </p>
    <p>
      Estudié Equitación y soy profesor titulado y después me uní al mundo del 3D. Mis estudios en 3D son de un grado
      superior de formación profesional llamado Animación, Modelado 3D y Espacios Interactivos en IED Madrid.
    </p>
    <h1 id="estudios"><a href="#estudios">Estudios</a></h1>
    <p>Ahora mismo estoy en ESNE Madrid estudiando el 2º año de la carrera de diseño de videojuegos</p>
    <p>
      <ImgZoom
        src="/posts/mi-primer-post/Fachada-ESNE-scaled.jpg"
        alt="Fachada-ESNE-scaled.jpg"
        width="1080"
        height="720" />
    </p>
    <h1 id="experiencia-laboral"><a href="#experiencia-laboral">Experiencia Laboral</a></h1>
    <p>
      Mi experiencia laboral a día de hoy en Septiembre de 2022 ha sido trabajando en Accenture(Consultoría) y creando
      Experiencias Virtuales 3D para Cupra(Coches)
    </p>
    <p><ImgZoom src="/posts/mi-primer-post/cupra.png" alt="Untitled" width="1889" height="860" /></p>
    <hr />
    <p>He sido el Artista Jefe de la red social Clivi y de todo el apartado de emotes/reacciones, que saldrá en 2023</p>
    <p>
      <ImgZoom src="/posts/mi-primer-post/stock_1_desktop.png" alt="stock_1_desktop.png" width="1920" height="1080" />
    </p>
    <hr />
    <p>Por otro lado, he dado clases particulares de Blender 3D (el programa en el que me especializo)</p>
    <h1 id="youtube"><a href="#youtube">Youtube</a></h1>
    <p>
      Por último, además de mantener este blog, publico desde hace 2 años tutoriales en YT en el canal de “str3Dlok”(Mi
      canal) donde me centro actualmente en tutoriales de todos los niveles del programa de Blender 3D, pero que con
      este proyecto pretendo hacer que es canal se haga un hueco en el mundo de los videojuegos y Developers
    </p>
    <p><ImgZoom src="/posts/mi-primer-post/logo_recto.png" alt="logo_recto.png" width="1080" height="1096" /></p>
    <hr />
    <p>Si quereis conocerme un poco mas:</p>
    <Youtube id="nxuju7-IrAo" />
    ---
  </article>
</Post>
