<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="idea-para-carreteras-gn"><a href="#idea-para-carreteras-gn">Idea para carreteras GN</a></h1>
    <!-- ![](./twitter.jpg) -->

    <p>En vez de usar la extrusion simple, instancia en vertices, asi que le daré una vuelta a mi sistema</p>
  </article>
</Post>
