<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="creador-edificios-geometry-nodes">
      <a href="#creador-edificios-geometry-nodes">Creador Edificios Geometry Nodes</a>
    </h1>
    <!-- Created by: str3Dlok
Created by 1: str3Dlok
Fecha Publicación: 02/01/2023
coverCaption: ⬆️ Hero image & info y link
description: Descripcion para SEO??
status: ☑️ Done
summary: Progreso Generador Edificios
tags: 3D, Blender
title: Generador Edificios Procedurales

![Untitled](Creador%20Edificios%20Geometry%20Nodes%206a940bee16d14638afe125e04bddcb64/Untitled.png) -->

    <p>
      Quedan aun por hacer ajustes para &quot;cambiar&quot; plantas vertical y horizontalmente pero al menos el tema de
      selecciones y orientaciones por Euler está bastante claro
    </p>
    <p>-Los nodos “Switch” para hacer selecciones son clave</p>
    <p>
      -Las seleciones se añaden como un “Instance Index” y con eso se puede elegir donde se instancia que
      selección(creada por medio del Switch)
    </p>
    <p>
      -Euler to Vector hace que podamos elegir un nuevo Vector de Dirección (tambien sirve para cambiar de Radianes a
      Grados)
    </p>
  </article>
</Post>
