<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="nodo-compare"><a href="#nodo-compare">Nodo Compare</a></h1>
    <p>
      Usando &quot;booleanos&quot; como el nodo &quot;Compare&quot; hace que las selecciones sean muy controlables. En
      este caso, si el area es menor o igual al area de 1m(3), se asigna el material Rojo, si no da ese resultado, no lo
      asigna (si no se usa Vector, no da resultado)
    </p>
    <!-- ![Nodo Compare](./NodoCompare.png) -->
  </article>
</Post>
