<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';

  import Youtube from '$lib/components/youtube.svelte';
</script>

<Post>
  <article slot="post_content">
    <h1 id="unreal-5-herramientas-2023"><a href="#unreal-5-herramientas-2023">Unreal 5 Herramientas 2023</a></h1>
    <!-- 
Created by: str3Dlok
Created by 1: str3Dlok
Fecha Publicación: 01/01/2023
coverCaption: ⬆️ Hero image & info y link
description: comparacion Unity Unreal
status: ☑️ Done
summary: Unreal Summary early 2023
tags: Blog, UE5
title: Unreal 5 Features -->

    <!-- ![1366_2000 (1).jpeg](Unreal%205%20Herramientas%202023%2064acbc155e1e4815ab41be3efbde8030/1366_2000_(1).jpeg) -->

    <p>
      He estado las conferencias de presentación de Unreal 5 y han hablado de nuevas funcionalidades/flujos de trabajo:
    </p>
    <ul>
      <li>
        Dividir Niveles por Escenas y Subescenas que se pueden ejecutar a placer en vez de montar todo en una escena
        general
      </li>
      <li>Chunking para dividir escenarios enormes de mudo abierto</li>
      <li>
        Crear Plugins para poder publicar packs completos en el marketplace(el proceso de crear plugin no es tan
        sencillo, requiere mucho control de programación para la exportación correcta)
      </li>
      <li>Funcionar por proyectos temporales de prueba y luego Migrar/Migrate a la escena limpia</li>
      <li>
        Migrar: exportar objetos(uasset) con todas sus referencias a escenas nuevas(es la mejor manera de trabajar por
        lo visto)
      </li>
      <li>
        Level Instancing es crear escenas con subescenas que se ejecutan a petición( incluso un objeto simple puede ser
        una escena y es mas eficiente que ir sacando Prefabs)
      </li>
      <li>
        World Partition(principio para chunking) ⇒ Enable Streaming ⇒ (Crea un sistema de grid para dividir nuestro
        mundo por chunks)
      </li>
      <li>
        Data Layers: Capas que tambien se pueden referenciar por código/nodos para quitar, poner, o modificar en tiempo
        real(para mejorar visualizacion en editor y rendimiento en Editor y juego final en diferentes plataformas
      </li>
      <li>HLOD: Lods automaticos</li>
      <li>Virtual Textures y Shadow Maps (han mejorado rendimiento y aumentado la calidad)</li>
      <li>
        Nanite y Lumen, que es de lo que mas se habla pero tiene su truco
        <ul>
          <li>Nanite: dividir geometria y aumentar detalle según de la distancia de la cámara</li>
          <li>Lumen: Iluminación Global Dinamica avanzada</li>
        </ul>
      </li>
    </ul>
    <h1 id="sobre-conferencia-de-how-to-make-better-blueprints">
      <a href="#sobre-conferencia-de-how-to-make-better-blueprints">
        Sobre Conferencia de “how to make better blueprints”:
      </a>
    </h1>
    <Youtube id="mW0IlgjF-iw" />

    <ul>
      <li>Level Instancing Blueprints (escenas y subescenas)</li>
      <li>
        Collapse Nodes (Hacer grupos de nodos, ya sabemos el flujo, conviene hacer grupos básicos que no se vayan a
        acceder, sino mejor tener todo visible para que no haya perdida)
      </li>
      <li>Usar Custom Events antes que ticks(consejo)</li>
      <li>
        Soft References (en vez de cargar todo el contenido del juego al incio, hacerlo cuando se requiera y asi reducir
        tiempos de carga y gpus saturadas)
      </li>
      <li>Exposed Funcitions</li>
      <li>Editor Utility</li>
      <li>
        Geoemtry Scripts (un principio como el de geometry nodes, pero sigue siendo experimental y es muy básico, asi
        que no usar por ahora)
      </li>
    </ul>
    <h1 id="sobre-video-how-to-get-better-performance-in-teams">
      <a href="#sobre-video-how-to-get-better-performance-in-teams">
        Sobre video “how to get better performance in teams”:
      </a>
    </h1>
    <Youtube id="GuIav71867E" />

    <ul>
      <li>
        Class Instance: Este es muy bueno porque permite hacer un Prefab “Padre” que contiene todas las propiedades y
        los hijos pueden usar las propiedades del padre o incluso crear nuevas y modificar a partir de la info del
        padre(y son independientes en todo momento)
      </li>
      <li>
        Tablas de Datos en CSV: Basicamente hacer interfaces en tablas para facilitar introducir objetos nuevos,
        modificar valores simples, etc. Sin tener que entrar en proyecto o nodos lo hace mucho mas facil para ajustes
        finales(ej: vida = 100, velocidad correr= 2.5)
      </li>
      <li>Event Dispatching and Binding (tengo que mirar bien este punto)</li>
      <li>
        Interfaces locales: Interesante porque se plantea que cada objeto tenga la interfaz que aparece cuando te
        acerques a este, pero en vez de referenciarlo a la interfaz del jugador, es una interfaz creada solo con el
        propio objeto y ejectuada solo cuando se pide(sino tendríamos asignadas a personaje miles de interfaces ocultas,
        así lo hace menos caotico)
      </li>
    </ul>
  </article>
</Post>
